### ISSUE TITLE
Disconnect sometimes throws error message

### ISSUE THREAD

**Issue by Overdrivr** [Overdrivr/pytelemetrycli#49]
```
:> disconnect
Disconnected.
:> Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\miniconda35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\miniconda35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\miniconda35\lib\site-packages\pytelemetrycli\runner.py", line 109, in
 run
    self.update()
  File "c:\miniconda35\lib\site-packages\pytelemetrycli\runner.py", line 63, in
update
    self.telemetryWrapper.update()
  File "c:\miniconda35\lib\site-packages\pytelemetry\pytelemetry.py", line 87, i
n update
    self.api.update()
  File "c:\miniconda35\lib\site-packages\pytelemetry\telemetry\telemetry.py", li
ne 202, in update
    self.delimiter.decode(c)
  File "c:\miniconda35\lib\site-packages\pytelemetry\telemetry\framing.py", line
 55, in decode
    for c in data:
TypeError: 'NoneType' object is not iterable


Disconnected.
:>
```

**Comment by Overdrivr** [comment]
Program then gets stuck on exit because clearly the running thread is not joinable. This is the root cause for issue #43
